version: '3'

networks:
  mock-server:

services:
  express:
    build:
      args:
        emulated_delay: "${EMULATED_DELAY-0}"
      context: .
    healthcheck:
      test: curl -f http://localhost:3000
    networks:
      mock-server:
    ports:
      - "3000:3000"
